### ISSUE TITLE
[FEATURE] Join/Leave Messages

### ISSUE THREAD

**Issue by KadTheHunter** [nomadjimbob/MCPEDiscordRelay#10]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Add the ability or option to show when players join/leave the server.

**Comment by nomadjimbob** [comment]
Scheduled for the next release

**Comment by nomadjimbob** [comment]
Feature available in [v1.0.8](/nomadjimbob/MCPEDiscordRelay/releases/tag/1.0.8) release
