### ISSUE TITLE
Server crash after player joins

### ISSUE THREAD

**Issue by MultipedBeatle** [nomadjimbob/MCPEDiscordRelay#11]
I had added MCPEDiscordRelay to my server to allow for people not playing to see chat and see who is currently online. This is my first time using this plugin.

Once I had it in my plugins folder, whenever I would join my server, it would stop the server after ten seconds or so. I tested this with and without other plugins and determined MCPEDiscordRelay to be the problem.

I'm using MCPEDiscordRelay version 1.0.8 with PocketMine-MP version 3.15.1.

All other plugins were disabled after the first crash, and MCPEDR was causing it when isolated.

The first crash, I had MailPlugin, Colormatic, and PersonaToSkin

No crash report was filed under my server, it just sent the stop command and the server closed.

**Comment by nomadjimbob** [comment]
Tried to replicate your issue with a fresh PocketMine 3.15.1 and MCPEDR on its own and cannot replicate the crash. Can you at least pass the server log when this happens? Does the plugin push any text through to Discord at any time?

**Comment by nomadjimbob** [comment]
Closed due to no response from author
