### ISSUE TITLE
[FEATURE] Disabling @everyone and @here 

### ISSUE THREAD

**Issue by KadTheHunter** [nomadjimbob/MCPEDiscordRelay#13]
**Is your feature request related to a problem?**
It would be great if there was an option in config to stop @everyone and @here pings from being sent. If I remember correctly, this can be done, and an older plugin did do it.

**Describe the solution you'd like**
Something like `enable_pings: <true/false>`

**Anything else?**
That's it, just a small request :)

**Comment by nomadjimbob** [comment]
This is now implemented in the 1.0.9 release
