### ISSUE TITLE
Dont work the weebhook url

### ISSUE THREAD

**Issue by UnEnanoMas** [nomadjimbob/MCPEDiscordRelay#2]
Server thread/INFO Enabling MCPEDiscordRelay v1.0.1
15.04 09:59:42 [Server] Server thread/INFO Webhook URL doesn't look right in config.yml
15.04 09:59:42 [Server] Server thread/INFO Plugin is Disabled

And i just get the same name of my server channel and the weebhook url like the url of my channel of discord, just copy paste

**Comment by nomadjimbob** [comment]
Does your webhook start with https://discordapp.com/api/webhooks/ ?

**Comment by UnEnanoMas** [comment]
https://discordapp.com/api/webhooks/699921534999068722/pnjAQ_AviRR....etc

**Comment by nomadjimbob** [comment]
I just tried your webhook and it accepted it, as it only verifies if the URL begins with https://discordapp.com/api/webhooks/  . Can you post your config.yml file with the end of the webhook removed?

**Comment by UnEnanoMas** [comment]
Dont support that file but i copy paste here

---
enabled: true         # Is plugin enabled?
discord_webhook_url: "https://discordapp.com/api/webhooks/699921534999068722/pnjAQ_AviRRo6nvdb5JewwotDR0TQ1kSLGNG23fTzCRtfJoa5Z4TXchat0eZDUm78-xH"	# The discord webhook URL
discord_webhook_name: "TornadusChat"	# The discord username
discord_webhook_refresh: 10	# Delay in updating discord
...

**Comment by nomadjimbob** [comment]
@UnEnanoMas posted the config file. Removed to safeguard the webhook.

**Comment by UnEnanoMas** [comment]
But its a bug or Discord api was bad?

**Comment by nomadjimbob** [comment]
Testing your config file on my own server now...

**Comment by nomadjimbob** [comment]
I don't get your error on my server. It connects to your discord channel fine

**Comment by UnEnanoMas** [comment]
Humm... i dont know why

**Comment by UnEnanoMas** [comment]
Im gonna try again

**Comment by UnEnanoMas** [comment]
Can u unload ur server for check it?

**Comment by nomadjimbob** [comment]
I've disconnected my server and removed your config.yml file

**Comment by UnEnanoMas** [comment]
Ok im gonna try

**Comment by UnEnanoMas** [comment]
Enabling MCPEDiscordRelay v1.0.1
15.04 10:36:43 [Server] Server thread/INFO Webhook URL doesn't look right in config.yml
15.04 10:36:43 [Server] Server thread/INFO Plugin is Disabled

Another time :(

I dont know if any plugin can intf whit him, i dont have more plugins for Discord or any like weebs

**Comment by nomadjimbob** [comment]
Can you post the entire server log?

**Comment by UnEnanoMas** [comment]
Yeah but just delete later

15.04 10:36:39 [Multicraft] Loading server properties
15.04 10:36:39 [Multicraft] Starting server!
15.04 10:36:39 [Multicraft] Loaded config for "AUTO UPDATING: PocketMine-MP Latest Stable (Current: 1.14.0 #1792)"
15.04 10:36:39 [Multicraft] JAR file not found, copying from global JAR directory
15.04 10:36:39 [Multicraft] Updating eula.txt file
15.04 10:36:42 [Server] Server thread/INFO Loading pocketmine.yml...
15.04 10:36:42 [Server] Server thread/INFO Loading server properties...
15.04 10:36:42 [Server] Server thread/INFO Selected English (eng) as the base language
15.04 10:36:42 [Server] Server thread/INFO Starting Minecraft: Bedrock Edition server version v1.14.0
15.04 10:36:42 [Server] Server thread/NOTICE Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
15.04 10:36:42 [Server] Server thread/NOTICE To disable authentication, set "xbox-auth" to "false" in server.properties.
15.04 10:36:42 [Server] Server thread/INFO Opening server on 54.39.38.201:25635
15.04 10:36:42 [Server] Server thread/INFO This server is running PocketMine-MP version 3.11.7
15.04 10:36:42 [Server] Server thread/INFO PocketMine-MP is distributed under the LGPL License
15.04 10:36:42 [Server] Server thread/INFO Loading resource packs...
15.04 10:36:42 [Server] Server thread/ERROR Could not load plugin 'DevTools': plugin exists
15.04 10:36:42 [Server] Server thread/INFO Loading RenameItems v1.1
15.04 10:36:42 [Server] Server thread/INFO Loading PlayerSkinStealer v1.0.0
15.04 10:36:42 [Server] Server thread/INFO Loading CustomAreas v1.2.1
15.04 10:36:42 [Server] Server thread/INFO Loading TapToArmor v1.0.2
15.04 10:36:42 [Server] Server thread/INFO Loading SizePlayer v1.1.0
15.04 10:36:42 [Server] Server thread/INFO Loading InfoUI v0.1
15.04 10:36:42 [Server] Server thread/INFO Loading MSpawns v2.2
15.04 10:36:42 [Server] Server thread/INFO Loading InventoryMonitor v1.3.3
15.04 10:36:42 [Server] Server thread/INFO Loading essentialsTP v1.2.2
15.04 10:36:42 [Server] Server thread/INFO Loading MaxEnchants v1.2.0
15.04 10:36:42 [Server] Server thread/INFO Loading BuilderTools v1.2.0-beta2
15.04 10:36:42 [Server] Server thread/INFO Loading FactionsPro v1.3.20
15.04 10:36:42 [Server] Server thread/INFO Loading NoVoid v1.1.0
15.04 10:36:42 [Server] Server thread/INFO Loading SkyWarsForPE v2.3-beta
15.04 10:36:42 [Server] Server thread/INFO Loaded SkyWars configuration into system.
15.04 10:36:42 [Server] Server thread/INFO Tracked and flashed 2 locales
15.04 10:36:42 [Server] Server thread/INFO Successfully loaded the sqlite driver
15.04 10:36:42 [Server] Server thread/INFO Loading JukeBox v1.0.1
15.04 10:36:42 [Server] Server thread/INFO Loading PlayerCrasher v1
15.04 10:36:42 [Server] Server thread/INFO Loading VanishV2 v1.5
15.04 10:36:42 [Server] Server thread/INFO Loading Rewards v3.0
15.04 10:36:42 [Server] Server thread/INFO Loading BowSound v1.1.2
15.04 10:36:42 [Server] Server thread/INFO Loading PlayerInfo v2.1.4
15.04 10:36:42 [Server] Server thread/INFO Loading StaffMode v1.1.0
15.04 10:36:42 [Server] Server thread/INFO Loading KDR v1.0.0
15.04 10:36:42 [Server] Server thread/INFO Loading Vehicles v0.1.1
15.04 10:36:42 [Server] Server thread/INFO Loading BanItem v2.3.3
15.04 10:36:42 [Server] Server thread/INFO Loading HealthTag v2.0.0
15.04 10:36:42 [Server] Server thread/INFO Loading PerWorldInventory v1.0.0
15.04 10:36:42 [Server] Server thread/INFO Loading EC-TableUI v1.1.2-pre
15.04 10:36:42 [Server] Server thread/INFO Loading CellPE v2.0.3
15.04 10:36:42 [Server] Server thread/INFO Loading Slapper v1.5.2
15.04 10:36:42 [Server] Server thread/INFO Loading DinoUI v1
15.04 10:36:42 [Server] Server thread/INFO Loading TeaSpoon v1.2.0
15.04 10:36:42 [Server] Server thread/INFO Loading Resources...
15.04 10:36:42 [Server] Server thread/INFO Loading DevTools v1.14.0
15.04 10:36:42 [Server] Server thread/INFO Loading MOTDShuffle v1.1.6
15.04 10:36:42 [Server] Server thread/INFO Loading Clothes v2.1.0
15.04 10:36:42 [Server] Server thread/INFO Loading Worlds v3.0.3
15.04 10:36:42 [Server] Server thread/INFO Loading RedstoneCircuit v2.0.0
15.04 10:36:42 [Server] Server thread/INFO Loading ScoreHud v5.1.1
15.04 10:36:42 [Server] Server thread/INFO Loading CustomSetting v1.0.3
15.04 10:36:42 [Server] Server thread/INFO Loading EconomyAPI v5.7.2
15.04 10:36:42 [Server] Server thread/INFO Loading FormAPI v1.3.0
15.04 10:36:42 [Server] Server thread/INFO Loading MyPlot v1.6.14
15.04 10:36:42 [Server] Server thread/INFO Loading PurePerms v1.4.3
15.04 10:36:42 [Server] Server thread/INFO Setting default language to 'en'
15.04 10:36:42 [Server] Server thread/NOTICE Multiworld support enabled.
15.04 10:36:42 [Server] Server thread/INFO Loading iProtector v3.1.1
15.04 10:36:42 [Server] Server thread/INFO Loading Texter v3.4.5
15.04 10:36:42 [Server] Server thread/INFO Selected English (en_us) as the base language
15.04 10:36:42 [Server] Server thread/INFO Commands was set to enabled
15.04 10:36:42 [Server] Server thread/INFO Loading AuctionHouse v1.0.9
15.04 10:36:42 [Server] Server thread/INFO Checking for updates...
15.04 10:36:42 [Server] Server thread/INFO Loading SellAll v1.3.0
15.04 10:36:42 [Server] Server thread/INFO Loading BlockSniper v3.2.3
15.04 10:36:42 [Server] Server thread/INFO Loading PureChat v1.4.11
15.04 10:36:42 [Server] Server thread/INFO Loading KillMoney v2.1.0
15.04 10:36:42 [Server] Server thread/INFO Enabling MSpawns v2.2
15.04 10:36:42 [Server] Server thread/INFO Enabling JukeBox v1.0.1
15.04 10:36:42 [Server] Server thread/INFO Enabling TeaSpoon v1.2.0
15.04 10:36:42 [Server] Server thread/INFO Loading...
15.04 10:36:42 [Server] INFO MMP""MM""YMM .M"""bgd
15.04 10:36:42 [Server] INFO P' MM `7 ,MI "Y
15.04 10:36:42 [Server] INFO MM .gP"Ya ,6"Yb. `MMb. `7MMpdMAo. ,pW"Wq. ,pW"Wq.`7MMpMMMb.
15.04 10:36:42 [Server] INFO MM ,M' Yb 8) MM `YMMNq. MM `Wb 6W' `Wb 6W' `Wb MM MM
15.04 10:36:42 [Server] INFO MM 8M"""""" ,pm9MM . `MM MM M8 8M M8 8M M8 MM MM
15.04 10:36:42 [Server] INFO MM YM. , 8M MM Mb dM MM ,AP YA. ,A9 YA. ,A9 MM MM
15.04 10:36:42 [Server] INFO .JMML.`Mbmmd' `Moo9^Yo.P"Ybmmd" MMbmmd' `Ybmd9' `Ybmd9'.JMML JMML.
15.04 10:36:42 [Server] INFO MM
15.04 10:36:42 [Server] INFO .JMML. PLEASE NO SMOKING FOOD RADIOS WITHOUT HEADPHONES BICYCLES
15.04 10:36:42 [Server] INFO Copyright (C) CortexPE 2017-2020
15.04 10:36:42 [Server] Server thread/INFO TeaSpoon is distributed under the AGPL License
15.04 10:36:42 [Server] Server thread/INFO Enabling DevTools v1.14.0
15.04 10:36:42 [Server] Server thread/INFO Loading EconomyJob v2.0.4
15.04 10:36:42 [Server] Server thread/INFO Loading Crossbow v1
15.04 10:36:42 [Server] Server thread/INFO Loading TornadusRank v1.0.0
15.04 10:36:42 [Server] Server thread/INFO Loading SlapperRotation v1.2.1
15.04 10:36:42 [Server] Server thread/INFO Loading 1vs1 v1.0.1
15.04 10:36:42 [Server] INFO array(2) {
15.04 10:36:42 [Server] INFO ["kits"]=>
15.04 10:36:42 [Server] INFO array(1) {
15.04 10:36:42 [Server] INFO ["diamond"]=>
15.04 10:36:42 [Server] INFO array(7) {
15.04 10:36:42 [Server] INFO ["helmet"]=>
15.04 10:36:42 [Server] INFO array(3) {
15.04 10:36:42 [Server] INFO [0]=>
15.04 10:36:42 [Server] INFO int(310)
15.04 10:36:42 [Server] INFO [1]=>
15.04 10:36:42 [Server] INFO int(0)
15.04 10:36:42 [Server] INFO [2]=>
15.04 10:36:42 [Server] INFO int(1)
15.04 10:36:42 [Server] INFO }
15.04 10:36:42 [Server] INFO ["chestplate"]=>
15.04 10:36:42 [Server] INFO array(3) {
15.04 10:36:42 [Server] INFO [0]=>
15.04 10:36:42 [Server] INFO int(311)
15.04 10:36:42 [Server] INFO [1]=>
15.04 10:36:42 [Server] INFO int(0)
15.04 10:36:42 [Server] INFO [2]=>
15.04 10:36:42 [Server] INFO int(1)
15.04 10:36:42 [Server] INFO }
15.04 10:36:42 [Server] INFO ["leggings"]=>
15.04 10:36:42 [Server] INFO array(3) {
15.04 10:36:42 [Server] INFO [0]=>
15.04 10:36:42 [Server] INFO int(312)
15.04 10:36:42 [Server] INFO [1]=>
15.04 10:36:42 [Server] INFO int(0)
15.04 10:36:42 [Server] INFO [2]=>
15.04 10:36:42 [Server] INFO int(1)
15.04 10:36:42 [Server] INFO }
15.04 10:36:42 [Server] INFO ["boots"]=>
15.04 10:36:42 [Server] INFO array(3) {
15.04 10:36:42 [Server] INFO [0]=>
15.04 10:36:42 [Server] INFO int(313)
15.04 10:36:42 [Server] INFO [1]=>
15.04 10:36:42 [Server] INFO int(0)
15.04 10:36:42 [Server] INFO [2]=>
15.04 10:36:42 [Server] INFO int(1)
15.04 10:36:42 [Server] INFO }
15.04 10:36:42 [Server] INFO [0]=>
15.04 10:36:42 [Server] INFO array(3) {
15.04 10:36:42 [Server] INFO [0]=>
15.04 10:36:42 [Server] INFO int(267)
15.04 10:36:42 [Server] INFO [1]=>
15.04 10:36:42 [Server] INFO int(0)
15.04 10:36:42 [Server] INFO [2]=>
15.04 10:36:42 [Server] INFO int(1)
15.04 10:36:42 [Server] INFO }
15.04 10:36:42 [Server] INFO [1]=>
15.04 10:36:42 [Server] INFO array(3) {
15.04 10:36:42 [Server] INFO [0]=>
15.04 10:36:42 [Server] INFO int(322)
15.04 10:36:42 [Server] INFO [1]=>
15.04 10:36:42 [Server] INFO int(0)
15.04 10:36:42 [Server] INFO [2]=>
15.04 10:36:42 [Server] INFO int(5)
15.04 10:36:42 [Server] INFO }
15.04 10:36:42 [Server] INFO [8]=>
15.04 10:36:42 [Server] INFO array(3) {
15.04 10:36:42 [Server] INFO [0]=>
15.04 10:36:42 [Server] INFO int(364)
15.04 10:36:42 [Server] INFO [1]=>
15.04 10:36:42 [Server] INFO int(0)
15.04 10:36:42 [Server] INFO [2]=>
15.04 10:36:42 [Server] INFO int(16)
15.04 10:36:42 [Server] INFO }
15.04 10:36:42 [Server] INFO }
15.04 10:36:42 [Server] INFO }
15.04 10:36:42 [Server] INFO ["hunger"]=>
15.04 10:36:42 [Server] INFO bool(true)
15.04 10:36:42 [Server] INFO }
15.04 10:36:42 [Server] Server thread/INFO Loading Friend v1.0.07
15.04 10:36:42 [Server] Server thread/INFO Loading EconomyShop v2.0.7
15.04 10:36:42 [Server] Server thread/INFO Loading AutoClearLagg v3.0.0
15.04 10:36:42 [Server] Server thread/INFO Loading SuperAlias v1.0.0
15.04 10:36:42 [Server] Server thread/INFO Loading MCPEDiscordRelay v1.0.1
15.04 10:36:42 [Server] Server thread/INFO Loading UltraCapes v1.7.5
15.04 10:36:42 [Server] Server thread/INFO Loading OnlineTime v1.3
15.04 10:36:42 [Server] Server thread/INFO Loading StarCore v1
15.04 10:36:42 [Server] Server thread/INFO Loading BossAnnouncement v2.0.0
15.04 10:36:42 [Server] Server thread/INFO Loading EDLB_FD v2.0.0
15.04 10:36:42 [Server] Server thread/INFO Loading ParkourR v1.0.0
15.04 10:36:42 [Server] Server thread/INFO Registered folder plugin loader
15.04 10:36:42 [Server] Server thread/INFO Enabling MOTDShuffle v1.1.6
15.04 10:36:42 [Server] Server thread/INFO has been activated!
15.04 10:36:42 [Server] Server thread/INFO Enabling RedstoneCircuit v2.0.0
15.04 10:36:42 [Server] Server thread/INFO Enabling MyPlot v1.6.14
15.04 10:36:42 [Server] Server thread/INFO Preparing world "Lobby"
15.04 10:36:42 [Server] Server thread/INFO Preparing world "teanether"
15.04 10:36:42 [Server] Server thread/INFO Preparing world "ender"
15.04 10:36:42 [Server] Server thread/INFO Enabling RenameItems v1.1
15.04 10:36:42 [Server] Server thread/INFO Enabling PlayerSkinStealer v1.0.0
15.04 10:36:42 [Server] Server thread/INFO Enabling CustomAreas v1.2.1
15.04 10:36:42 [Server] Server thread/INFO Enabling TapToArmor v1.0.2
15.04 10:36:42 [Server] Server thread/INFO Enabling SizePlayer v1.1.0
15.04 10:36:42 [Server] Server thread/INFO Enabling InfoUI v0.1
15.04 10:36:42 [Server] Server thread/INFO Information has been revealed
15.04 10:36:42 [Server] Server thread/INFO Enabling InventoryMonitor v1.3.3
15.04 10:36:42 [Server] Server thread/INFO Selected English (eng) as the base language
15.04 10:36:42 [Server] Server thread/INFO Enabling essentialsTP v1.2.2
15.04 10:36:42 [Server] Server thread/INFO essentialsTP+ loading...
15.04 10:36:42 [Server] Server thread/INFO [INFO] loading [config.yml]....
15.04 10:36:42 [Server] Server thread/INFO [INFO] loading [config.yml] DONE
15.04 10:36:42 [Server] Server thread/INFO essentialsTP+ loaded!
15.04 10:36:42 [Server] Server thread/INFO Enabling MaxEnchants v1.2.0
15.04 10:36:42 [Server] Server thread/INFO Enabling BuilderTools v1.2.0-beta2
15.04 10:36:42 [Server] Server thread/INFO Enabling FactionsPro v1.3.20
15.04 10:36:42 [Server] Server thread/INFO Add AntiSpamPro to ban rude Faction names
15.04 10:36:42 [Server] Server thread/INFO Enabling NoVoid v1.1.0
15.04 10:36:42 [Server] Server thread/INFO NoVoid creado por NashanPlaysYT
15.04 10:36:42 [Server] Server thread/INFO Enabling SkyWarsForPE v2.3-beta
15.04 10:36:42 [Server] Server thread/INFO Starting SkyWarsForPE modules...
15.04 10:36:42 [Server] Server thread/INFO Loaded chest random configuration.
15.04 10:36:42 [Server] Server thread/INFO Locating arena files...
15.04 10:36:42 [Server] Server thread/INFO Preparing world "LobbySW"
15.04 10:36:42 [Server] Server thread/INFO Bosque - Arena loaded and enabled
15.04 10:36:42 [Server] Server thread/INFO Preparing world "world"
15.04 10:36:42 [Server] Server thread/INFO Default - Arena disabled
15.04 10:36:42 [Server] Server thread/INFO No TopWinners spawn location were found.
15.04 10:36:42 [Server] Server thread/INFO Please reconfigure TopWinners spawn locations
15.04 10:36:42 [Server] Server thread/INFO SkyWarsForPE has been enabled
15.04 10:36:42 [Server] Server thread/INFO Enabling PlayerCrasher v1
15.04 10:36:42 [Server] Server thread/INFO enabled!
15.04 10:36:42 [Server] Server thread/INFO Enabling VanishV2 v1.5
15.04 10:36:42 [Server] Server thread/INFO Enabling Rewards v3.0
15.04 10:36:42 [Server] Server thread/INFO Enabling BowSound v1.1.2
15.04 10:36:42 [Server] Server thread/INFO Enabling PlayerInfo v2.1.4
15.04 10:36:42 [Server] Server thread/INFO Enabling StaffMode v1.1.0
15.04 10:36:42 [Server] Server thread/INFO StaffMode On! By NashanPlays
15.04 10:36:42 [Server] Server thread/INFO Enabling KDR v1.0.0
15.04 10:36:42 [Server] Server thread/NOTICE YamlProvider successfully enabled.
15.04 10:36:42 [Server] Server thread/INFO KillCounter Plugin Enabled.
15.04 10:36:42 [Server] Server thread/INFO Enabling Vehicles v0.1.1
15.04 10:36:42 [Server] Server thread/INFO Enabling BanItem v2.3.3
15.04 10:36:42 [Server] Server thread/INFO Enabling HealthTag v2.0.0
15.04 10:36:42 [Server] Server thread/INFO Enabling PerWorldInventory v1.0.0
15.04 10:36:42 [Server] Server thread/INFO Enabling EC-TableUI v1.1.2-pre
15.04 10:36:42 [Server] Server thread/INFO Enabling CellPE v2.0.3
15.04 10:36:42 [Server] Server thread/INFO Enabling Slapper v1.5.2
15.04 10:36:42 [Server] INFO 2.1.4[10:36:42] [Server thread/INFO]: Enabling DinoUI v1
15.04 10:36:42 [Server] Server thread/INFO Plugin DinoUI Dibuat Oleh AlvinMask
15.04 10:36:42 [Server] Server thread/INFO Enabling Clothes v2.1.0
15.04 10:36:42 [Server] Server thread/INFO Enabling Worlds v3.0.3
15.04 10:36:42 [Server] Server thread/INFO Enabling ScoreHud v5.1.1
15.04 10:36:42 [Server] Server thread/INFO Checking for updates...
15.04 10:36:42 [Server] Server thread/INFO Enabling CustomSetting v1.0.3
15.04 10:36:42 [Server] Server thread/INFO Enabling EconomyAPI v5.7.2
15.04 10:36:43 [Server] Server thread/NOTICE The update server is now online!
15.04 10:36:43 [Server] Server thread/NOTICE Database provider was set to: Yaml
15.04 10:36:43 [Server] Server thread/INFO Enabling FormAPI v1.3.0
15.04 10:36:43 [Server] Server thread/INFO Enabling PurePerms v1.4.3
15.04 10:36:43 [Server] Server thread/NOTICE Set data provider to YAMLv1.
15.04 10:36:43 [Server] Server thread/INFO Enabling iProtector v3.1.1
15.04 10:36:43 [Server] Server thread/INFO Enabling Texter v3.4.5
15.04 10:36:43 [Server] Server thread/INFO Enabling AuctionHouse v1.0.9
15.04 10:36:43 [Server] Server thread/INFO Enabling SellAll v1.3.0
15.04 10:36:43 [Server] Server thread/INFO Enabling BlockSniper v3.2.3
15.04 10:36:43 [Server] Server thread/INFO [BlockSniper] Language selected: en
15.04 10:36:43 [Server] Server thread/INFO Enabling PureChat v1.4.11
15.04 10:36:43 [Server] Server thread/NOTICE FactionsPro < 1.4 support enabled.
15.04 10:36:43 [Server] Server thread/INFO Enabling KillMoney v2.1.0
15.04 10:36:43 [Server] Server thread/INFO Enabling EconomyJob v2.0.4
15.04 10:36:43 [Server] Server thread/INFO Enabling Crossbow v1
15.04 10:36:43 [Server] Server thread/INFO Enabling TornadusRank v1.0.0
15.04 10:36:43 [Server] Server thread/NOTICE TornadusRank a la orden de Milos
15.04 10:36:43 [Server] Server thread/INFO Enabling SlapperRotation v1.2.1
15.04 10:36:43 [Server] Server thread/INFO Enabling 1vs1 v1.0.1
15.04 10:36:43 [Server] Server thread/INFO Preparing world "Waitingroom"
15.04 10:36:43 [Server] Server thread/INFO Preparing world "DM-Castle"
15.04 10:36:43 [Server] Server thread/INFO Preparing world "TheVolcanPvPFlat"
15.04 10:36:43 [Server] Server thread/INFO Enabling Friend v1.0.07
15.04 10:36:43 [Server] Server thread/INFO Friend Has started.
15.04 10:36:43 [Server] Server thread/INFO Enabling EconomyShop v2.0.7
15.04 10:36:43 [Server] Server thread/NOTICE Data provider was set to: Yaml
15.04 10:36:43 [Server] Server thread/INFO Enabling AutoClearLagg v3.0.0
15.04 10:36:43 [Server] Server thread/INFO Enabling SuperAlias v1.0.0
15.04 10:36:43 [Server] Server thread/INFO You do not have SimpleAuth
15.04 10:36:43 [Server] Server thread/INFO You can only get a players alias if he/she is online!
15.04 10:36:43 [Server] Server thread/INFO Enabling MCPEDiscordRelay v1.0.1
15.04 10:36:43 [Server] Server thread/INFO Webhook URL doesn't look right in config.yml
15.04 10:36:43 [Server] Server thread/INFO Plugin is Disabled
15.04 10:36:43 [Server] Server thread/INFO Enabling UltraCapes v1.7.5
15.04 10:36:43 [Server] Server thread/INFO Enabling OnlineTime v1.3
15.04 10:36:43 [Server] Server thread/INFO Enabling StarCore v1
15.04 10:36:43 [Server] Server thread/NOTICE StarCore iniciado
15.04 10:36:43 [Server] Server thread/NOTICE Starcore. Falta FormAPI
15.04 10:36:43 [Server] Server thread/INFO Enabling BossAnnouncement v2.0.0
15.04 10:36:43 [Server] Server thread/INFO Enabling EDLB_FD v2.0.0
15.04 10:36:43 [Server] Server thread/INFO EDLB by FoxyDroiid
15.04 10:36:43 [Server] Server thread/INFO Preparing world "DamnedTunnels"
15.04 10:36:43 [Server] Server thread/INFO Enabling ParkourR v1.0.0
15.04 10:36:43 [Server] Server thread/NOTICE ParkourR activado
15.04 10:36:43 [Server] Server thread/INFO Starting GS4 status listener
15.04 10:36:43 [Server] Server thread/INFO Setting query port to 25635
15.04 10:36:43 [Server] Server thread/INFO Query running on 54.39.38.201:25635
15.04 10:36:43 [Server] Server thread/INFO Default game type: Survival Mode
15.04 10:36:43 [Server] Server thread/INFO If you find this project useful, please consider donating to support development: https://patreon.com/pocketminemp
15.04 10:36:43 [Server] Startup Done (1.213s)! For help, type "help" or "?"
15.04 10:36:43 [Server] Server thread/NOTICE Addon BasicAddon successfully enabled.
15.04 10:36:43 [Server] Server thread/NOTICE Addon EconomyApiAddon successfully enabled.
15.04 10:36:43 [Server] Server thread/NOTICE Addon FactionsProAddon successfully enabled.
15.04 10:36:43 [Server] Server thread/NOTICE Addon KDRAddon successfully enabled.
15.04 10:36:43 [Server] Server thread/NOTICE Addon OnlineTimeAddon successfully enabled.
15.04 10:36:43 [Server] Server thread/NOTICE Latest version: v3.4.5 / No update needed
15.04 10:36:43 [Server] Server thread/INFO No new updates were found. You are using the latest version.
15.04 10:36:43 [Server] Server thread/INFO No new updates were found. You are using the latest version.
15.04 10:36:43 [Server] Server thread/INFO (Addon Update Info) No new updates for addon BasicAddon were found. You are using the latest version.
15.04 10:36:43 [Server] Server thread/INFO (Addon Update Info) No new updates for addon EconomyApiAddon were found. You are using the latest version.
15.04 10:36:43 [Server] Server thread/INFO (Addon Update Info) No new updates for addon KDRAddon were found. You are using the latest version.
15.04 10:36:43 [Server] Server thread/INFO (Addon Update Info) No new updates for addon OnlineTimeAddon were found. You are using the latest version.
15.04 10:36:43 [Server] Server thread/INFO (Addon Update Info) No new updates for addon FactionsProAddon were found. You are using the latest version.
15.04 10:36:44 [Server] Server thread/INFO Preparing world "Mina"
15.04 10:36:44 [Server] Server thread/INFO Preparing world "Spawn"
15.04 10:36:44 [Server] Server thread/INFO Preparing world "Shop"
15.04 10:36:44 [Server] Server thread/INFO Preparing world "Survival"
15.04 10:36:44 [Server] Server thread/INFO Uft: 3 texts / Ft: 6 texts have been generated
15.04 10:36:45 [Server] Server thread/INFO Started to load arenas worlds...
15.04 10:36:45 [Server] Server thread/INFO Preparing world "BedWars8x1"
15.04 10:36:45 [Server] Server thread/INFO Preparing world "SkyWarsForPE"

**Comment by nomadjimbob** [comment]
[config.yml.zip](https://github.com/nomadjimbob/MCPEDiscordRelay/files/4480708/config.yml.zip)
Can you replace your config.yml with this one (unzip it first) and see if it works?

**Comment by UnEnanoMas** [comment]
Ok

**Comment by UnEnanoMas** [comment]
Im gonna try and now i have a folder whit the name Macoxs

Try off ur server pls

**Comment by UnEnanoMas** [comment]
Enabling MCPEDiscordRelay v1.0.1
15.04 10:51:07 [Server] Server thread/INFO Webhook URL doesn't look right in config.yml
15.04 10:51:07 [Server] Server thread/INFO Plugin is Disabled

Another time, i think its impossib

**Comment by nomadjimbob** [comment]
My guess is another plugin on your server is interfering with the plugin. Try disabling all your other plugins on your server and see if the issue persists.

**Comment by UnEnanoMas** [comment]
Ok

**Comment by nomadjimbob** [comment]
Deleted server log and config.yml files that had sensitive data

**Comment by UnEnanoMas** [comment]
15.04 11:01:36 [Multicraft] Starting server!
15.04 11:01:36 [Multicraft] Loaded config for "AUTO UPDATING: PocketMine-MP Latest Stable (Current: 1.14.0 #1792)"
15.04 11:01:36 [Multicraft] JAR file not found, copying from global JAR directory
15.04 11:01:36 [Multicraft] Updating eula.txt file
15.04 11:01:39 [Server] Server thread/INFO Loading pocketmine.yml...
15.04 11:01:39 [Server] Server thread/INFO Loading server properties...
15.04 11:01:39 [Server] Server thread/INFO Selected English (eng) as the base language
15.04 11:01:39 [Server] Server thread/INFO Starting Minecraft: Bedrock Edition server version v1.14.0
15.04 11:01:39 [Server] Server thread/NOTICE Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
15.04 11:01:39 [Server] Server thread/NOTICE To disable authentication, set "xbox-auth" to "false" in server.properties.
15.04 11:01:39 [Server] Server thread/INFO Opening server on xxxxxxxxxxxxxx
15.04 11:01:39 [Server] Server thread/INFO This server is running PocketMine-MP version 3.11.7
15.04 11:01:39 [Server] Server thread/INFO PocketMine-MP is distributed under the LGPL License
15.04 11:01:39 [Server] Server thread/INFO Loading resource packs...
15.04 11:01:39 [Server] Server thread/INFO Preparing world "Lobby"
15.04 11:01:39 [Server] Server thread/INFO Starting GS4 status listener
15.04 11:01:39 [Server] Server thread/INFO Setting query port to xxxxx
15.04 11:01:39 [Server] Server thread/INFO Query running on 54.39.38.201:25635
15.04 11:01:39 [Server] Server thread/INFO Default game type: Survival Mode
15.04 11:01:39 [Server] Server thread/INFO If you find this project useful, please consider donating to support development: https://patreon.com/pocketminemp
15.04 11:01:39 [Server] Startup Done (0.27s)! For help, type "help" or "?"

**Comment by UnEnanoMas** [comment]
Now the plugin dont start xd whit only 1 plugin on the folders of plugin

**Comment by nomadjimbob** [comment]
Just to confirm, your plugins folder is named plugins, not plugin?

**Comment by UnEnanoMas** [comment]
yeah is named plugins

**Comment by nomadjimbob** [comment]
Try putting another plugin into the plugins folder and see if that loads

**Comment by UnEnanoMas** [comment]
15.04 11:12:24 [Server] Server thread/INFO Loading resource packs...
15.04 11:12:24 [Server] Server thread/INFO Loading MorphX v1.1.0
15.04 11:12:24 [Server] Server thread/INFO Preparing world "Lobby"
15.04 11:12:24 [Server] Server thread/INFO Enabling MorphX v1.1.0
15.04 11:12:24 [Server] Server thread/INFO Starting GS4 status listener

Yeah he do but no Discord

**Comment by nomadjimbob** [comment]
Try downloading it again and see https://github.com/nomadjimbob/MCPEDiscordRelay/releases/download/v1.0.1/MCPEDiscordRelay.phar.zip

**Comment by UnEnanoMas** [comment]
It work!

**Comment by nomadjimbob** [comment]
Connected to Discord?

**Comment by UnEnanoMas** [comment]
Now im gonna try, but discc ur server pls xd

**Comment by UnEnanoMas** [comment]
Or its mine? lol

**Comment by UnEnanoMas** [comment]
Wait a moment

**Comment by UnEnanoMas** [comment]
Yeah he actually work

Ty so much :D

**Comment by UnEnanoMas** [comment]
[11:22:44] [Server thread/INFO]: There are 0/50 players online:
[11:22:44] [Server thread/INFO]:

How can i disable this msg?

He send me at 10 sec all times

**Comment by nomadjimbob** [comment]
MCPEDiscordRelay is reporting what is being put into your console. That includes what plugins push to your console. You need to find the plugin that is doing that and disable it.

**Comment by nomadjimbob** [comment]
I can update the plugin to have an option to disable all [Server thread/INFO] messages posted to discord however, you will then only see player chat, if that helps

**Comment by nomadjimbob** [comment]
Added config.yml option "send_console: true|false" in  release v1.0.2
