### ISSUE TITLE
more of a question

### ISSUE THREAD

**Issue by MistakingManx** [nomadjimbob/MCPEDiscordRelay#3]
Sorry to bother you with a question, but I'm trying to add the ability to have a footer to the webhook, like how it is on JS `footer: {text: ""}`, but I'm not sure how to handle this.

I don't work with the Discord HTTP API..

**Comment by nomadjimbob** [comment]
You would need to modify the $curlopts in the [Broadcast.php](https://github.com/nomadjimbob/MCPEDiscordRelay/blob/91e33cfc45d597f8542988b8b01a66f90b859ab5/src/nomadjimbob/MCPEDiscordRelay/Broadcast.php#L22) file

Something to like:
`
$curlopts = [
    "content" => $msg,
    "username" =>  $this->main->getDiscordWebHookName,
    "embeds" = [
        "title" => "the title",
        "description" => "the description",
        "color" => 7506394,
        "footer" => [
            "text" => "this is my footer"
        ]
]
 `

Before I consider adding it as a feature, how would you using the footer embed? as just static text so these embeds could just be additional conf options?

**Comment by nomadjimbob** [comment]
Using the Embed feature set is now available in 1.0.6. You can set them using the config.yml options:

discord_webhook_title
discord_webhook_description
discord_webhook_color
discord_webhook_footer
