### ISSUE TITLE
crash[BUG] 

### ISSUE THREAD

**Issue by royaljacques** [nomadjimbob/MCPEDiscordRelay#6]
acktrace:
#0 plugins/MCPEDiscordRelay.phar/src/nomadjimbob/MCPEDiscordRelay/Broadcast(17): nomadjimbob\MCPEDiscordRelay\Broadcast->sendToDiscord(string[5] nolog, string[1199] MCPEDiscordRelay enabled...[38;5;87m[18:33:22] .[m.[38;5;231m[Server thread/INFO, NULL )
#1 src/pocketmine/scheduler/TaskHandler(134): nomadjimbob\MCPEDiscordRelay\Broadcast->onRun(integer 1)
#2 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 1)
#3 src/pocketmine/plugin/PluginManager(643): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1)
#4 src/pocketmine/Server(2380): pocketmine\plugin\PluginManager->tickSchedulers(integer 1)
#5 src/pocketmine/Server(2143): pocketmine\Server->tick()
#6 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
#7 src/pocketmine/Server(1584): pocketmine\Server->start()
#8 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[45] C:\Users\El..ve\Desktop\PocketMine-MP-3.12.0\, string[53] C:\Users\El..ve\Desktop\PocketMine-MP-3.12.0\plugins\)
#9 src/pocketmine/PocketMine(295): pocketmine\server()
#10 (11): require(string[100] phar://C:/Users/El..ve/Desktop/PocketMine-MP-3.12.0/PocketMine-MP.phar/src/pocke)

**Comment by nomadjimbob** [comment]
Can you provide the version of the plugin you are using? It doesn't appear to be the (latest)[https://github.com/nomadjimbob/MCPEDiscordRelay/releases/latest] version. I also need to see your server log and config.yml files (if you post your config.yml, change the discord ID in the webhook to XXX.

If you are not comfortable placing your server log here, you can email it to me directly (james.collins@outlook.com.au)

**Comment by nomadjimbob** [comment]
Closed due to lack of response from the creator
