### ISSUE TITLE
[BUG] Plugin not working on iOS server?

### ISSUE THREAD

**Issue by ImNotDev** [nomadjimbob/MCPEDiscordRelay#9]
**Describe the bug**
I’m on IOS and I tried the plugin it doesn’t work

**Expected behavior**

**Version of MCPEDiscordRelay and PocketMine:**
 - MCPEDiscordRelay Version [e.g 1.0.6]
 - PocketMine Version [e.g. 1.13.2]

**Was it working in a previous version of MCPEDiscordRelay?**
I never try

**Other Plugins**
Have you tried disabling other plugs to check if there is a conflict?
No

What are the other plugins that you have installed?
MCPETodiscord

**Anything else?**
Add any other information about the problem here.

**Comment by nomadjimbob** [comment]
How are you running the PocketMine server on iOS and what version of PocketMine are you running?

**Comment by nomadjimbob** [comment]
Closed due to no response from author
